name: "Test setup-nuget-exe"

on: [pull_request, push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nuget-version: [latest, preview]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with:
        nuget-version: ${{ matrix.nuget-version }}
        nuget-api-key: 4003d786-cc37-4004-bfdf-c4f3e8ef9b3a
    - run: nuget
